#compose docker
version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_URL=sqlite:///./database.db # Define la URL de la base de datos
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload